"""rename department

Revision ID: 01a70dfd9463
Revises: a678ab9d6b70
Create Date: 2025-06-13 21:00:55.381459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a70dfd9463'
down_revision = 'a678ab9d6b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###